name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pytest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install pipx
      run: pip install pipx
    - name: Install dependencies
      run: pipx install maturin
    - name: Build
      run: echo "nightly" > rust-toolchain;	maturin develop; rm rust-toolchain
    - name: Run tests
      run: pytest
